spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=quindioflix_owner
spring.datasource.password=quindioflix2025
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.show-sql=true