spring.application.name=quindioflix

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=quindioflix_owner
spring.datasource.password=quindioflix2025
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=8080

jwt.secret=quindioflixSecretKey2025MustBeAtLeast256BitsLongForHS256
jwt.expiration=86400000
