-- =============================================================================
-- 00_LIMPIEZA.sql
-- Limpiar objetos existentes
-- Ejecutar como SYS en SQL Developer
-- Si hay error, continuar con el siguiente
-- =============================================================================

-- Tablas (ignorar errores si no existen)
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE REPORTES_CONTENIDO PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PAGOS PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CALIFICACIONES PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE FAVORITOS PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE REPRODUCCIONES PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE EPISODIOS PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEMPORADAS PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CONTENIDO_RELACIONADO PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CONTENIDO_GENERO PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CONTENIDO PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE GENEROS PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CATEGORIAS PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PERFILES PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USUARIOS PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE EMPLEADOS PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DEPARTAMENTOS PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PLANES PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Secuencias
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_REPORTES';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PAGOS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CALIFICACIONES';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_FAVORITOS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_REPRODUCCIONES';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EMPLEADOS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DEPARTAMENTOS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EPISODIOS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TEMPORADAS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CONTENIDO';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_GENEROS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CATEGORIAS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PERFILES';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USUARIOS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PLANES';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Triggers
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_REPORTES_ID';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_PAGOS_ID';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_CALIFICACIONES_ID';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_FAVORITOS_ID';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_REPRODUCCIONES_ID';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_EMPLEADOS_ID';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_DEPARTAMENTOS_ID';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_EPISODIOS_ID';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_TEMPORADAS_ID';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_CONTENIDO_ID';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_GENEROS_ID';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_CATEGORIAS_ID';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_PERFILES_ID';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_USUARIOS_ID';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_PLANES_ID';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Verificar
SELECT table_name FROM user_tables WHERE table_name IN (
    'REPORTES_CONTENIDO', 'PAGOS', 'CALIFICACIONES', 'FAVORITOS', 
    'REPRODUCCIONES', 'EMPLEADOS', 'DEPARTAMENTOS', 'EPISODIOS', 
    'TEMPORADAS', 'CONTENIDO_RELACIONADO', 'CONTENIDO_GENERO', 
    'CONTENIDO', 'GENEROS', 'CATEGORIAS', 'PERFILES', 
    'USUARIOS', 'PLANES'
) ORDER BY table_name;