-- =============================================================================
-- QUINDIOFLIX - Seguridad: Usuarios y Roles de Oracle
-- Universidad del Quindío · Bases de Datos II · 2025-1
-- Sprint 8: Nucleo Tematico 5
-- =============================================================================

SET LINESIZE 200;

-- =============================================================================
-- CREACION DE ROLES
-- =============================================================================

-- Eliminar roles existentes si existen
DROP ROLE ROL_ADMIN CASCADE;
DROP ROLE ROL_ANALISTA CASCADE;
DROP ROLE ROL_SOPORTE CASCADE;
DROP ROLE ROL_CONTENIDO CASCADE;

-- Crear roles
CREATE ROLE ROL_ADMIN;
CREATE ROLE ROL_ANALISTA;
CREATE ROLE ROL_SOPORTE;
CREATE ROLE ROL_CONTENIDO;

-- =============================================================================
-- PRIVILEGIOS POR ROL
-- =============================================================================

-- ROL_ADMIN: CRUD en todas las tablas + ejecutar todos los SPs + CREATE/DROP USER
GRANT SELECT, INSERT, UPDATE, DELETE ON USUARIOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON PERFILES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON PLANES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CATEGORIAS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON GENEROS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONTENIDO TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONTENIDO_GENERO TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONTENIDO_RELACIONADO TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON TEMPORADAS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON EPISODIOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON DEPARTAMENTOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON EMPLEADOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON REPRODUCCIONES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON FAVORITOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CALIFICACIONES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON PAGOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON REPORTES_CONTENIDO TO ROL_ADMIN;

-- Ejecutar procedimienSTOS
GRANT EXECUTE ON SP_REGISTRAR_USUARIO TO ROL_ADMIN;
GRANT EXECUTE ON SP_CAMBIAR_PLAN TO ROL_ADMIN;
GRANT EXECUTE ON SP_REPORTE_CONSUMO TO ROL_ADMIN;
GRANT EXECUTE ON SP_REGISTRO_COMPLETO_USUARIO TO ROL_ADMIN;
GRANT EXECUTE ON SP_RENOVACION_MENSUAL TO ROL_ADMIN;
GRANT EXECUTE ON SP_ELIMINAR_CUENTA TO ROL_ADMIN;
GRANT EXECUTE ON SP_ACTUALIZAR_POPULARIDAD TO ROL_ADMIN;
GRANT EXECUTE ON FN_CALCULAR_MONTO TO ROL_ADMIN;
GRANT EXECUTE ON FN_CONTENIDO_RECOMENDADO TO ROL_ADMIN;

-- Vistas materializadas
GRANT SELECT ON MV_CONTENIDO_POPULAR TO ROL_ADMIN;
GRANT SELECT ON MV_INGRESOS_MENSUALES TO ROL_ADMIN;
GRANT EXECUTE ON MV_CONTENIDO_POPULAR TO ROL_ADMIN;
GRANT EXECUTE ON MV_INGRESOS_MENSUALES TO ROL_ADMIN;

-- ROL_ANALISTA: SELECT en todas las tablas + ejecutar SPs de reporte + acceso a VMs
GRANT SELECT ON USUARIOS TO ROL_ANALISTA;
GRANT SELECT ON PERFILES TO ROL_ANALISTA;
GRANT SELECT ON PLANES TO ROL_ANALISTA;
GRANT SELECT ON CATEGORIAS TO ROL_ANALISTA;
GRANT SELECT ON GENEROS TO ROL_ANALISTA;
GRANT SELECT ON CONTENIDO TO ROL_ANALISTA;
GRANT SELECT ON CONTENIDO_GENERO TO ROL_ANALISTA;
GRANT SELECT ON CONTENIDO_RELACIONADO TO ROL_ANALISTA;
GRANT SELECT ON TEMPORADAS TO ROL_ANALISTA;
GRANT SELECT ON EPISODIOS TO ROL_ANALISTA;
GRANT SELECT ON DEPARTAMENTOS TO ROL_ANALISTA;
GRANT SELECT ON EMPLEADOS TO ROL_ANALISTA;
GRANT SELECT ON REPRODUCCIONES TO ROL_ANALISTA;
GRANT SELECT ON FAVORITOS TO ROL_ANALISTA;
GRANT SELECT ON CALIFICACIONES TO ROL_ANALISTA;
GRANT SELECT ON PAGOS TO ROL_ANALISTA;
GRANT SELECT ON REPORTES_CONTENIDO TO ROL_ANALISTA;

GRANT EXECUTE ON SP_REPORTE_SUSCRIPCIONES_VENCIDAS TO ROL_ANALISTA;
GRANT EXECUTE ON SP_REPORTE_CONSUMO TO ROL_ANALISTA;
GRANT EXECUTE ON FN_CALCULAR_MONTO TO ROL_ANALISTA;
GRANT SELECT ON MV_CONTENIDO_POPULAR TO ROL_ANALISTA;
GRANT SELECT ON MV_INGRESOS_MENSUALES TO ROL_ANALISTA;

-- ROL_SOPORTE: SELECT en USUARIOS/PERFILES/PAGOS, INSERT/UPDATE en PAGOS, ejecutar SP_CAMBIAR_PLAN
GRANT SELECT ON USUARIOS TO ROL_SOPORTE;
GRANT SELECT ON PERFILES TO ROL_SOPORTE;
GRANT SELECT ON PLANES TO ROL_SOPORTE;
GRANT SELECT ON PAGOS TO ROL_SOPORTE;
GRANT INSERT, UPDATE ON PAGOS TO ROL_SOPORTE;
GRANT EXECUTE ON SP_CAMBIAR_PLAN TO ROL_SOPORTE;

-- ROL_CONTENIDO: CRUD en CONTENIDO/TEMPORADAS/EPISODIOS/GENEROS + SELECT en REPRODUCCIONES/CALIFICACIONES
GRANT SELECT, INSERT, UPDATE, DELETE ON CONTENIDO TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON TEMPORADAS TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON EPISODIOS TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON GENEROS TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON CATEGORIAS TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONTENIDO_GENERO TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONTENIDO_RELACIONADO TO ROL_CONTENIDO;
GRANT SELECT ON REPRODUCCIONES TO ROL_CONTENIDO;
GRANT SELECT ON CALIFICACIONES TO ROL_CONTENIDO;

-- =============================================================================
-- CREACION DE PERFIL DE RECURSOS
-- =============================================================================

-- Eliminar perfil existente
DROP PROFILE PERFIL_QUINDIOFLIX LIMIT;

-- Crear perfil con limites
CREATE PROFILE PERFIL_QUINDIOFLIX LIMIT
    SESSIONS_PER_USER        3
    IDLE_TIME                30
    FAILED_LOGIN_ATTEMPTS    5
    PASSWORD_LOCK_TIME       1/24
    CONNECT_TIME             480;

-- =============================================================================
-- CREACION DE USUARIOS ORACLE
-- =============================================================================

-- Eliminar usuarios existentes
DROP USER usr_admin CASCADE;
DROP USER usr_analista CASCADE;
DROP USER usr_soporte CASCADE;
DROP USER usr_contenido CASCADE;

-- Crear usuarios
CREATE USER usr_admin IDENTIFIED BY Admin2025#
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    PROFILE PERFIL_QUINDIOFLIX;

CREATE USER usr_analista IDENTIFIED BY Analista2025#
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP;

CREATE USER usr_soporte IDENTIFIED BY Soporte2025#
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    PROFILE PERFIL_QUINDIOFLIX;

CREATE USER usr_contenido IDENTIFIED BY Contenido2025#
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    PROFILE PERFIL_QUINDIOFLIX;

-- Asignar roles
GRANT ROL_ADMIN TO usr_admin;
GRANT ROL_ANALISTA TO usr_analista;
GRANT ROL_SOPORTE TO usr_soporte;
GRANT ROL_CONTENIDO TO usr_contenido;

-- Asignar privilegio de sesion
GRANT CREATE SESSION TO usr_admin;
GRANT CREATE SESSION TO usr_analista;
GRANT CREATE SESSION TO usr_soporte;
GRANT CREATE SESSION TO usr_contenido;

-- =============================================================================
-- VERIFICAR
-- =============================================================================

SELECT username, account_status, profile, created
FROM user_users
WHERE username IN ('USR_ADMIN', 'USR_ANALISTA', 'USR_SOPORTE', 'USR_CONTENIDO');

SELECT granted_role, admin_option FROM user_role_privs
WHERE grantee IN ('USR_ADMIN', 'USR_ANALISTA', 'USR_SOPORTE', 'USR_CONTENIDO');

-- =============================================================================
-- DEMOSTRACION DE RESTRICCIONES DE ACCESO
-- =============================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED;

-- Conectarse como usr_soporte e intentar DELETE FROM CONTENIDO (debe fallar)
-- Esto fallara con ORA-01031: insufficient privileges

/*
-- En SQL Developer como usr_soporte:
DELETE FROM CONTENIDO WHERE id_contenido = 1;
-- Error: ORA-01031: insufficient privileges
*/

-- Conectarse como usr_analista e intentar INSERT en PAGOS (debe fallar)
/*
-- En SQL Developer como usr_analista:
INSERT INTO PAGOS (id_usuario, fecha_pago, monto, metodo_pago, estado_pago, fecha_vencimiento)
VALUES (1, SYSDATE, 12990, 'TARJETA_CREDITO', 'EXITOSO', SYSDATE + 30);
-- Error: ORA-01031: insufficient privileges
*/

-- Conectarse como usr_contenido e intentar SELECT en PAGOS (debe fallar)
/*
-- En SQL Developer como usr_contenido:
SELECT * FROM PAGOS;
-- Error: ORA-00942: table or view does not exist
*/

BEGIN
    DBMS_OUTPUT.PUT_LINE('========================================');
    DBMS_OUTPUT.PUT_LINE('ROLES Y PRIVILEGIOS ASIGNADOS');
    DBMS_OUTPUT.PUT_LINE('========================================');
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('ROL_ADMIN:');
    DBMS_OUTPUT.PUT_LINE('  - Todos los privilegios en todas las tablas');
    DBMS_OUTPUT.PUT_LINE('  - Ejecutar todos los stored procedures');
    DBMS_OUTPUT.PUT_LINE('  - Acceso a vistas materializadas');
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('ROL_ANALISTA:');
    DBMS_OUTPUT.PUT_LINE('  - SELECT en todas las tablas');
    DBMS_OUTPUT.PUT_LINE('  - Ejecutar SPs de reporte');
    DBMS_OUTPUT.PUT_LINE('  - Acceso a VMs');
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('ROL_SOPORTE:');
    DBMS_OUTPUT.PUT_LINE('  - SELECT en USUARIOS, PERFILES, PAGOS');
    DBMS_OUTPUT.PUT_LINE('  - INSERT/UPDATE en PAGOS');
    DBMS_OUTPUT.PUT_LINE('  - Ejecutar SP_CAMBIAR_PLAN');
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('ROL_CONTENIDO:');
    DBMS_OUTPUT.PUT_LINE('  - CRUD en CONTENIDO, TEMPORADAS,');
    DBMS_OUTPUT.PUT_LINE('    EPISODIOS, GENEROS, CATEGORIAS');
    DBMS_OUTPUT.PUT_LINE('  - SELECT en REPRODUCCIONES,');
    DBMS_OUTPUT.PUT_LINE('    CALIFICACIONES');
    DBMS_OUTPUT.PUT_LINE('========================================');
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('USUARIOS CREADOS:');
    DBMS_OUTPUT.PUT_LINE('  - usr_admin / Admin2025# (ROL_ADMIN)');
    DBMS_OUTPUT.PUT_LINE('  - usr_analista / Analista2025# (ROL_ANALISTA)');
    DBMS_OUTPUT.PUT_LINE('  - usr_soporte / Soporte2025# (ROL_SOPORTE)');
    DBMS_OUTPUT.PUT_LINE('  - usr_contenido / Contenido2025# (ROL_CONTENIDO)');
    DBMS_OUTPUT.PUT_LINE('========================================');
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_line('PERFIL_QUINDIOFLIX:');
    DBMS_OUTPUT.PUT_LINE('  - SESSIONS_PER_USER: 3');
    DBMS_OUTPUT.PUT_LINE('  - IDLE_TIME: 30 minutos');
    DBMS_OUTPUT.PUT_LINE('  - FAILED_LOGIN_ATTEMPTS: 5');
    DBMS_OUTPUT.PUT_LINE('  - PASSWORD_LOCK_TIME: 1 hora');
    DBMS_OUTPUT.PUT_LINE('  - CONNECT_TIME: 480 minutos');
    DBMS_OUTPUT.PUT_LINE('========================================');
END;

/